/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.QuickSort;

import org.junit.jupiter.api.Test;

import java.util.ArrayList;

import static com.QuickSort.App.QuickSort;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    public void quickSortTest() {
        ArrayList<Integer> arrayList = new ArrayList<>();
        arrayList.add(8);
        arrayList.add(4);
        arrayList.add(23);
        arrayList.add(42);
        arrayList.add(16);
        arrayList.add(15);
        QuickSort(arrayList , 0 , arrayList.size()-1);
        ArrayList<Integer> arr2 = new ArrayList<>();
        arr2.add(4);
        arr2.add(8);
        arr2.add(15);
        arr2.add(16);
        arr2.add(23);
        arr2.add(42);
        assertEquals(arrayList , arr2);
    }
}
