/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.linked;

public class App {


    public static void main(String[] args) {


//        System.out.println(number2);
//        System.out.println(zipLists(number1 , number2));
    }

    public static LinkedList zipLists(LinkedList number1 , LinkedList number2){
        LinkedList<Integer> number3 = new LinkedList<Integer>();
        Node current1 = number1.head;
        Node current2 = number2.head;
        while (current1 != null || current2 != null ){
            if (current1 == null){

                    number3.append((Integer) current2.value);
                    current2 = current2.next;
                    continue;
                }
            if (current2 == null){
                number3.append((Integer) current1.value);
                current1 =current1.next;
                continue;
            }

                number3.append((Integer) current1.value);
                number3.append((Integer) current2.value);
                current1 =current1.next;
                current2 = current2.next;
        }
        return number3;
    }


}
