/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.linked;

public class App {


    public static void main(String[] args) {
        LinkedList<Integer> number = new LinkedList<>();

        System.out.println(number.include(1));
    }
}
