/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.InsertionSort;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test
    public void insertSortTest(){
        int[] arr = {8,4,23,42,16,15};
        int[] arr1 = App.insertionSort(arr);
        int[] arr2 = {4,8,15,16,23,42};
        assertArrayEquals(arr1 ,arr2);
    }
}
