/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.treeIntersection;

import com.treeIntersection.structure.HashMap;
import com.treeIntersection.structure.TreeIntersection;
import org.junit.jupiter.api.Test;

import java.util.HashSet;
import java.util.Set;

import static com.treeIntersection.App.treeIntersection;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    public void testKey(){
        TreeIntersection<Integer> treeIntersection1 = new TreeIntersection<>();
        treeIntersection1.add(15);
        treeIntersection1.add(20);
        treeIntersection1.add(3);
        treeIntersection1.add(4);
        treeIntersection1.add(5);


        TreeIntersection<Integer> treeIntersection2 = new TreeIntersection<>();
        treeIntersection2.add(15);
        treeIntersection2.add(20);
        treeIntersection2.add(7);
        treeIntersection2.add(9);
        treeIntersection2.add(8);

        Set<String> set = treeIntersection(treeIntersection1 , treeIntersection2);

        Set<String> exp = new HashSet<>();
        exp.add("15");
        exp.add("20");

        assertEquals(set.toString() , exp.toString());
    }
}
